'use client';

import React, { useState } from 'react';
import { Download, Copy, Check, Lock } from 'lucide-react';

interface AnonymizationRule {
  id: string;
  original: string;
  replacement: string;
  occurrences: number;
}

interface AnonymizedReportProps {
  caseId: string;
  reportId: string;
  reportContent: string;
  anonymizationRules: AnonymizationRule[];
  confidentialityLevel: 'PÚBLICO' | 'CONFIDENCIAL' | 'ALTAMENTE_CONFIDENCIAL';
  generatedAt: string;
  generatedBy: string;
}

const getConfidentialityColor = (level: 'PÚBLICO' | 'CONFIDENCIAL' | 'ALTAMENTE_CONFIDENCIAL') => {
  switch (level) {
    case 'PÚBLICO':
      return 'var(--salvia)';
    case 'CONFIDENCIAL':
      return 'var(--amarillo)';
    case 'ALTAMENTE_CONFIDENCIAL':
      return 'var(--rojo)';
  }
};

export const AnonymizedReport: React.FC<AnonymizedReportProps> = ({
  caseId,
  reportId,
  reportContent,
  anonymizationRules,
  confidentialityLevel,
  generatedAt,
  generatedBy,
}) => {
  const [copiedContent, setCopiedContent] = useState(false);

  const handleCopyContent = () => {
    navigator.clipboard.writeText(reportContent);
    setCopiedContent(true);
    setTimeout(() => setCopiedContent(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([reportContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `report-${reportId}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const confidentialityColor = getConfidentialityColor(confidentialityLevel);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: '1.5rem',
        padding: '1.5rem',
        backgroundColor: 'var(--card)',
        borderRadius: 'var(--radius)',
        border: '1px solid var(--border)',
        width: '100%',
        boxSizing: 'border-box',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '0.75rem',
        }}
      >
        <div
          style={{
            fontSize: '0.75rem',
            fontWeight: 700,
            color: 'var(--salvia)',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
          }}
        >
          Reporte Anonimizado
        </div>

        <h3
          style={{
            margin: 0,
            fontSize: '1.25rem',
            fontWeight: 700,
            color: 'var(--grafito)',
          }}
        >
          Documento Procesado
        </h3>
      </div>

      {/* Metadata Bar */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '1rem',
          padding: '1rem',
          backgroundColor: 'var(--papel)',
          borderRadius: '6px',
          border: '1px solid var(--border)',
        }}
      >
        {/* Confidentiality */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '0.75rem',
          }}
        >
          <Lock size={18} style={{ color: confidentialityColor, flexShrink: 0 }} />
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              gap: '0.25rem',
            }}
          >
            <span
              style={{
                fontSize: '0.75rem',
                fontWeight: 700,
                color: 'var(--grafito)',
                opacity: 0.6,
                textTransform: 'uppercase',
              }}
            >
              Confidencialidad
            </span>
            <span
              style={{
                fontSize: '0.875rem',
                fontWeight: 700,
                color: confidentialityColor,
              }}
            >
              {confidentialityLevel === 'PÚBLICO'
                ? 'Público'
                : confidentialityLevel === 'CONFIDENCIAL'
                  ? 'Confidencial'
                  : 'Altamente Confidencial'}
            </span>
          </div>
        </div>

        {/* Generated By */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '0.25rem',
          }}
        >
          <span
            style={{
              fontSize: '0.75rem',
              fontWeight: 700,
              color: 'var(--grafito)',
              opacity: 0.6,
              textTransform: 'uppercase',
            }}
          >
            Generado por
          </span>
          <span
            style={{
              fontSize: '0.875rem',
              fontWeight: 600,
              color: 'var(--grafito)',
            }}
          >
            {generatedBy}
          </span>
        </div>

        {/* Date */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '0.25rem',
          }}
        >
          <span
            style={{
              fontSize: '0.75rem',
              fontWeight: 700,
              color: 'var(--grafito)',
              opacity: 0.6,
              textTransform: 'uppercase',
            }}
          >
            Fecha de Generación
          </span>
          <span
            style={{
              fontSize: '0.875rem',
              fontWeight: 600,
              color: 'var(--grafito)',
            }}
          >
            {new Date(generatedAt).toLocaleDateString('es-ES')}
          </span>
        </div>
      </div>

      {/* Report Content */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '0.75rem',
        }}
      >
        <div
          style={{
            fontSize: '0.875rem',
            fontWeight: 700,
            color: 'var(--grafito)',
            textTransform: 'uppercase',
            letterSpacing: '0.05em',
          }}
        >
          Contenido del Reporte
        </div>

        <div
          style={{
            position: 'relative',
            padding: '1rem',
            backgroundColor: 'var(--papel)',
            borderRadius: '6px',
            border: '1px solid var(--border)',
            maxHeight: '400px',
            overflowY: 'auto',
          }}
        >
          <p
            style={{
              margin: 0,
              fontSize: '0.875rem',
              color: 'var(--grafito)',
              lineHeight: 1.6,
              whiteSpace: 'pre-wrap',
              wordBreak: 'break-word',
            }}
          >
            {reportContent}
          </p>

          {/* Copy Button */}
          <button
            onClick={handleCopyContent}
            style={{
              position: 'absolute',
              top: '0.75rem',
              right: '0.75rem',
              backgroundColor: 'var(--salvia)',
              border: 'none',
              borderRadius: '4px',
              padding: '6px 12px',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem',
              color: 'white',
              fontSize: '0.8125rem',
              fontWeight: 600,
              transition: 'opacity 0.2s ease',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.opacity = '0.9';
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.opacity = '1';
            }}
          >
            {copiedContent ? (
              <>
                <Check size={16} />
                <span>Copiado</span>
              </>
            ) : (
              <>
                <Copy size={16} />
                <span>Copiar</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Anonymization Rules Table */}
      {anonymizationRules.length > 0 && (
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '0.75rem',
          }}
        >
          <div
            style={{
              fontSize: '0.875rem',
              fontWeight: 700,
              color: 'var(--grafito)',
              textTransform: 'uppercase',
              letterSpacing: '0.05em',
            }}
          >
            Términos Anonimizados: {anonymizationRules.length}
          </div>

          <div
            style={{
              overflowX: 'auto',
              borderRadius: '6px',
              border: '1px solid var(--border)',
            }}
          >
            <table
              style={{
                width: '100%',
                borderCollapse: 'collapse',
                backgroundColor: 'var(--papel)',
              }}
            >
              <thead>
                <tr style={{ borderBottom: '2px solid var(--border)' }}>
                  <th
                    style={{
                      padding: '0.75rem',
                      textAlign: 'left',
                      fontSize: '0.8125rem',
                      fontWeight: 700,
                      color: 'var(--grafito)',
                      backgroundColor: 'rgba(0, 0, 0, 0.02)',
                    }}
                  >
                    Original
                  </th>
                  <th
                    style={{
                      padding: '0.75rem',
                      textAlign: 'left',
                      fontSize: '0.8125rem',
                      fontWeight: 700,
                      color: 'var(--grafito)',
                      backgroundColor: 'rgba(0, 0, 0, 0.02)',
                    }}
                  >
                    Reemplazo
                  </th>
                  <th
                    style={{
                      padding: '0.75rem',
                      textAlign: 'center',
                      fontSize: '0.8125rem',
                      fontWeight: 700,
                      color: 'var(--grafito)',
                      backgroundColor: 'rgba(0, 0, 0, 0.02)',
                    }}
                  >
                    Ocurrencias
                  </th>
                </tr>
              </thead>
              <tbody>
                {anonymizationRules.map((rule, idx) => (
                  <tr
                    key={rule.id}
                    style={{
                      borderBottom: '1px solid var(--border)',
                      backgroundColor: idx % 2 === 0 ? 'transparent' : 'rgba(0, 0, 0, 0.01)',
                    }}
                  >
                    <td
                      style={{
                        padding: '0.75rem',
                        fontSize: '0.875rem',
                        color: 'var(--grafito)',
                        fontWeight: 500,
                      }}
                    >
                      <code
                        style={{
                          padding: '2px 6px',
                          backgroundColor: 'rgba(0, 0, 0, 0.05)',
                          borderRadius: '3px',
                          fontFamily: 'monospace',
                          fontSize: '0.8125rem',
                        }}
                      >
                        {rule.original}
                      </code>
                    </td>
                    <td
                      style={{
                        padding: '0.75rem',
                        fontSize: '0.875rem',
                        color: 'var(--salvia)',
                        fontWeight: 600,
                      }}
                    >
                      <code
                        style={{
                          padding: '2px 6px',
                          backgroundColor: 'rgba(73, 180, 142, 0.1)',
                          borderRadius: '3px',
                          fontFamily: 'monospace',
                          fontSize: '0.8125rem',
                        }}
                      >
                        {rule.replacement}
                      </code>
                    </td>
                    <td
                      style={{
                        padding: '0.75rem',
                        fontSize: '0.875rem',
                        color: 'var(--grafito)',
                        textAlign: 'center',
                        fontWeight: 600,
                      }}
                    >
                      {rule.occurrences}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Actions */}
      <div
        style={{
          display: 'flex',
          gap: '0.75rem',
          paddingTop: '0.75rem',
          borderTop: '1px solid var(--border)',
        }}
      >
        <button
          onClick={handleDownload}
          style={{
            flex: 1,
            padding: '0.75rem',
            backgroundColor: 'var(--salvia)',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            fontSize: '0.875rem',
            fontWeight: 600,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '0.5rem',
            transition: 'opacity 0.2s ease',
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.opacity = '0.9';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.opacity = '1';
          }}
        >
          <Download size={18} />
          <span>Descargar Reporte</span>
        </button>
      </div>

      {/* Footer */}
      <div
        style={{
          fontSize: '0.75rem',
          color: 'var(--grafito)',
          opacity: 0.6,
          textAlign: 'center',
          paddingTop: '0.5rem',
        }}
      >
        ID del Reporte: {reportId}
      </div>
    </div>
  );
};
